# Generated by Django 4.0.2 on 2022-03-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('auto_delete_setting', models.IntegerField(default=1)),
                ('account', models.CharField(max_length=128, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('gender', models.CharField(max_length=128, null=True)),
                ('birthday', models.CharField(max_length=128, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
