# Generated by Django 4.0.2 on 2022-03-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('auto_delete_setting', models.IntegerField(default=3)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('auto_delete_setting', models.IntegerField(choices=[(0, 'ATONCE'), (1, 'SESSION'), (2, 'ONEDAY'), (3, 'TWODAY')], default=1)),
                ('account', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=128, null=True)),
                ('birthday', models.DateField(blank=True, max_length=128, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='myUserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('content', models.CharField(max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ManyToManyField(related_name='from_user', to='hour84.myUser')),
                ('to_user', models.ManyToManyField(related_name='to_user', to='hour84.myUser')),
            ],
        ),
        migrations.CreateModel(
            name='myRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('content', models.CharField(max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ManyToManyField(to='hour84.myUser')),
                ('to_room', models.ManyToManyField(to='hour84.myRoom')),
            ],
        ),
    ]
