# Generated by Django 4.0.2 on 2022-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('auto_delete_setting', models.IntegerField(default=3)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='myUserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('content', models.CharField(max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ManyToManyField(related_name='from_user', to='hour84.myUser')),
                ('to_user', models.ManyToManyField(related_name='to_user', to='hour84.myUser')),
            ],
        ),
        migrations.CreateModel(
            name='myRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('content', models.CharField(max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ManyToManyField(to='hour84.myUser')),
                ('to_room', models.ManyToManyField(to='hour84.myRoom')),
            ],
        ),
    ]
