# Generated by Django 4.0.2 on 2022-03-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='auto_delete_setting',
            field=models.IntegerField(choices=[(0, 'NEVER'), (1, 'SESSION'), (2, 'ONEDAY'), (3, 'TWODAY')], default=1),
        ),
    ]
