# Generated by Django 4.0.3 on 2022-03-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0002_rename_name_myuser_username_remove_myuser_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myroom',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='myroommessage',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='myusermessage',
            name='uuid',
        ),
    ]
