# Generated by Django 4.0.2 on 2022-03-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0003_alter_myuser_auto_delete_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='account',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
