# Generated by Django 4.0.3 on 2022-03-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0004_rename_name_myroom_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(to='hour84.myuser'),
        ),
    ]
