# Generated by Django 4.0.2 on 2022-03-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0004_alter_myuser_account_alter_myuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='account',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='uuid',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
