# Generated by Django 4.0.3 on 2022-03-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0005_myuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
