# Generated by Django 4.0.3 on 2022-03-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0006_myuser_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='auto_delete_setting',
            new_name='setting',
        ),
    ]
