# Generated by Django 4.0.3 on 2022-03-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0007_rename_auto_delete_setting_myuser_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='online',
        ),
        migrations.AddField(
            model_name='myuser',
            name='from_db',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
