# Generated by Django 4.0.3 on 2022-03-11 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hour84', '0008_remove_myuser_birthday_remove_myuser_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='from_db',
            new_name='real_in_db',
        ),
    ]
